#!/bin/sh

source sys_debug.sh

print_ln $LEVEL_INFO "$0"

export PT_DEST_OS_DRIVE="$INVALID"
export PT_MAX_PARTITION_NAME="$INVALID"
export PT_MAX_PARTITION_SIZE="$INVALID"
export PT_MAX_PARTITION_LOCA="$INVALID"
export PT_MAX_PARTITION_FS_TYPE="$INVALID"
export PT_VG_NAME="vg0"

export PT_MOPS_PARTITION_SH_FILE="$SYS_EXPECT_MOPS_PARTITION_SH_FILE"
export PT_KICKOFF_SEGMENT_FILE="$SYS_EXPECT_KICKOFF_SEGMENT_FILE"
export PT_KS_SEGMENT_BOOTLOADER_FILE="$SYS_EXPECT_KS_SEGMENT_BOOTLOADER_FILE"
export PT_KS_SEGMENT_HARDDRIVE_FILE="$SYS_EXPECT_KS_SEGMENT_HARDDRIVE_FILE"
export PT_KS_SEGMENT_PARTITION_FILE="$SYS_EXPECT_KS_SEGMENT_PARTITION_FILE"
export PT_KS_SEGMENT_PRE_FILE="$SYS_EXPECT_KS_SEGMENT_PRE_FILE"
export PT_KS_SEGMENT_POST_FILE="$SYS_EXPECT_KS_SEGMENT_POST_FILE"
